version: '3.9'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Painel Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.encurtador.rule=PathPrefix(`/`)"
      - "traefik.http.services.encurtador.loadbalancer.server.port=8080"
      - "traefik.http.routers.encurtador.entrypoints=web"

    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: encurtador
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
