services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik

  app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.encurtador.rule=Host(`short.local`)"
      - "traefik.http.services.encurtador.loadbalancer.server.port=5000"
      - "traefik.http.routers.encurtador.entrypoints=web"
    depends_on:
      - db
    volumes:
      - datakeys:/root/.aspnet/DataProtection-Keys
    networks:
      - traefik

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: encurtador
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  datakeys:

networks:
  traefik:
    external: true
